-- Raw-payload retention (DATA-PRIVACY.md "Retention" / open item 2): scout_snapshots.raw
-- is nulled out by the prune-raw-payloads cron once a snapshot is older than
-- RAW_PAYLOAD_RETENTION_DAYS, so the column can no longer be NOT NULL. Same shape and
-- same reasoning as 20260730120000_post_comment_text_nullable.
--
-- Additive, non-destructive: DROP NOT NULL only widens what the column accepts. Existing
-- rows keep their payload until the cron actually clears them, and nothing needs
-- backfilling. Hand-written rather than autogenerated on purpose — this table holds real
-- production data and a drafted drop+add would lose every stored payload.
ALTER TABLE "scout_snapshots" ALTER COLUMN "raw" DROP NOT NULL;
